#应用配置
spring:
  redis:
      timeout: 3000  #连接超时时间
      jedis.pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5    # 连接池中的最大空闲连接
        min-idle: 2    # 连接池中的最小空闲连接
      host: localhost
      port: 6379
      database: 0
      password:
  datasource:
      defaultDataSource: test
      dynamic:
        test:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password:
          url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          hikari:
            maximum-pool-size: 100
            minimum-idle: 20
            data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
  freemarker:
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type : text/html
      enabled : true
      expose-request-attributes : false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
      order: 1
      settings:
        template_update_delay: 0
        default_encoding: UTF-8
        classic_compatible: true