#应用配置
spring:
  redis:
      timeout: 3000  #连接超时时间
      jedis.pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 2000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5    # 连接池中的最大空闲连接
        min-idle: 2    # 连接池中的最小空闲连接
      host:
      port:
      database:
      password:
  datasource:
      defaultDataSource: customBusDB
      dynamic:
        customBusDB:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          username:
          password:
          url:
          hikari:
            maximum-pool-size: 100
            minimum-idle: 20
            data-source-properties:
              cachePrepStmts: true
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true